import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:signlang/firebase_options.dart';

/// Connects the app to the Firebase project uzsl-7cd39 (Authentication + push notifications).
/// The data itself stays in the UzSL API.
class FirebaseSetup {
  FirebaseSetup._();

  static bool _ready = false;

  /// False when the Firebase config is missing: email sign-in and push are then off.
  static bool get ready => _ready;

  static Future<void> init() async {
    try {
      // lib/firebase_options.dart is generated by: flutterfire configure --project=uzsl-7cd39
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      _ready = true;
    } catch (e) {
      debugPrint('Firebase off: $e');
    }
  }

  /// Ends the Firebase session too when the user logs out.
  static Future<void> signOut() async {
    if (_ready) await FirebaseAuth.instance.signOut();
  }
}
