CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "phone" varchar(20) UNIQUE,
  "password" varchar(128),
  "full_name" varchar(150),
  "avatar" varchar(100),
  "language" varchar(2) NOT NULL DEFAULT 'uz',
  "proficiency" varchar(20) NOT NULL DEFAULT 'beginner',
  "timezone" varchar(64) NOT NULL DEFAULT 'Asia/Tashkent',
  "learning_goal" varchar(20),
  "referral_source" varchar(20),
  "daily_goal_minutes" smallint NOT NULL DEFAULT 10,
  "onboarding_completed" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_staff" boolean NOT NULL DEFAULT false,
  "is_superuser" boolean NOT NULL DEFAULT false,
  "last_login" timestamp,
  "date_joined" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "social_accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "provider" varchar(10) NOT NULL,
  "uid" varchar(255) NOT NULL,
  "email" varchar(254),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "phone_otps" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone" varchar(20) NOT NULL,
  "purpose" varchar(20) NOT NULL,
  "code_hash" varchar(64) NOT NULL,
  "attempts" smallint NOT NULL DEFAULT 0,
  "is_used" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp NOT NULL
);

CREATE TABLE "notification_settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE NOT NULL,
  "general" boolean NOT NULL DEFAULT true,
  "daily_reminders" boolean NOT NULL DEFAULT true,
  "goal_reminders" boolean NOT NULL DEFAULT false,
  "new_achievements" boolean NOT NULL DEFAULT true,
  "news" boolean NOT NULL DEFAULT true,
  "activity_reminders" boolean NOT NULL DEFAULT false
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "name_ru" varchar(100),
  "name_en" varchar(100),
  "slug" varchar(100) UNIQUE NOT NULL,
  "description" varchar(255),
  "icon" varchar(100),
  "unit_label" varchar(30) NOT NULL DEFAULT 'imo-ishora',
  "is_emergency" boolean NOT NULL DEFAULT false,
  "is_featured" boolean NOT NULL DEFAULT false,
  "order" integer NOT NULL DEFAULT 0
);

CREATE TABLE "signs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word" varchar(255) NOT NULL,
  "transcription" varchar(255),
  "translation_ru" varchar(255),
  "translation_en" varchar(255),
  "kind" varchar(10) NOT NULL DEFAULT 'word',
  "thumbnail" varchar(100),
  "meaning" text,
  "hand_shape" text,
  "movement" text,
  "example_sentence" varchar(500),
  "example_video" varchar(100),
  "is_published" boolean NOT NULL DEFAULT true,
  "view_count" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "sign_categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sign_id" bigint NOT NULL,
  "category_id" bigint NOT NULL
);

CREATE TABLE "sign_related" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_sign_id" bigint NOT NULL,
  "to_sign_id" bigint NOT NULL
);

CREATE TABLE "sign_videos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sign_id" bigint NOT NULL,
  "video" varchar(100) NOT NULL,
  "angle" varchar(10) NOT NULL DEFAULT 'front',
  "duration_ms" integer,
  "order" smallint NOT NULL DEFAULT 0
);

CREATE TABLE "saved_signs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "sign_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "recent_views" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "sign_id" bigint NOT NULL,
  "viewed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "offline_packages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" varchar(50) UNIQUE NOT NULL,
  "title" varchar(100) NOT NULL,
  "file" varchar(100) NOT NULL,
  "size_bytes" bigint NOT NULL DEFAULT 0,
  "version" integer NOT NULL DEFAULT 1,
  "is_active" boolean NOT NULL DEFAULT true,
  "order" smallint NOT NULL DEFAULT 0,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "courses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "title_ru" varchar(100),
  "title_en" varchar(100),
  "slug" varchar(100) UNIQUE NOT NULL,
  "subtitle" varchar(255),
  "description" varchar(255),
  "icon" varchar(100),
  "unit_label" varchar(30) NOT NULL DEFAULT 'so'z',
  "order" integer NOT NULL DEFAULT 0,
  "is_published" boolean NOT NULL DEFAULT true
);

CREATE TABLE "lessons" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "title" varchar(150) NOT NULL,
  "description" text,
  "thumbnail" varchar(100),
  "duration_minutes" smallint NOT NULL DEFAULT 5,
  "difficulty" varchar(10) NOT NULL DEFAULT 'easy',
  "xp_reward" integer NOT NULL DEFAULT 30,
  "is_onboarding" boolean NOT NULL DEFAULT false,
  "is_published" boolean NOT NULL DEFAULT true,
  "order" integer NOT NULL DEFAULT 0
);

CREATE TABLE "lesson_signs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "sign_id" bigint NOT NULL,
  "order" smallint NOT NULL DEFAULT 0
);

CREATE TABLE "exercises" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "type" varchar(20) NOT NULL,
  "prompt" varchar(255),
  "sign_id" bigint,
  "explanation" varchar(500),
  "order" smallint NOT NULL DEFAULT 0
);

CREATE TABLE "exercise_options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exercise_id" bigint NOT NULL,
  "text" varchar(255),
  "image" varchar(100),
  "sign_id" bigint,
  "is_correct" boolean NOT NULL DEFAULT false,
  "position" smallint
);

CREATE TABLE "user_lesson_progress" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "lesson_id" bigint NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'in_progress',
  "best_accuracy" smallint NOT NULL DEFAULT 0,
  "completed_at" timestamp,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "lesson_attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "lesson_id" bigint NOT NULL,
  "started_at" timestamp NOT NULL DEFAULT (now()),
  "finished_at" timestamp,
  "correct_count" smallint NOT NULL DEFAULT 0,
  "total_count" smallint NOT NULL DEFAULT 0,
  "accuracy" smallint NOT NULL DEFAULT 0,
  "xp_earned" integer NOT NULL DEFAULT 0,
  "duration_seconds" integer NOT NULL DEFAULT 0
);

CREATE TABLE "exercise_answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attempt_id" bigint NOT NULL,
  "exercise_id" bigint NOT NULL,
  "answer" jsonb NOT NULL,
  "is_correct" boolean NOT NULL,
  "answered_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "exercise_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "exercise_id" bigint NOT NULL,
  "reason" varchar(20) NOT NULL,
  "comment" text,
  "status" varchar(20) NOT NULL DEFAULT 'new',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_stats" (
  "user_id" bigint PRIMARY KEY,
  "total_xp" integer NOT NULL DEFAULT 0,
  "level" smallint NOT NULL DEFAULT 1,
  "current_streak" smallint NOT NULL DEFAULT 0,
  "longest_streak" smallint NOT NULL DEFAULT 0,
  "last_active_date" date,
  "signs_learned" integer NOT NULL DEFAULT 0,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "daily_activities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "date" date NOT NULL,
  "minutes" smallint NOT NULL DEFAULT 0,
  "xp" integer NOT NULL DEFAULT 0,
  "lessons_completed" smallint NOT NULL DEFAULT 0,
  "correct_answers" integer NOT NULL DEFAULT 0,
  "total_answers" integer NOT NULL DEFAULT 0
);

CREATE TABLE "activity_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "source" varchar(20) NOT NULL,
  "started_at" timestamp NOT NULL,
  "ended_at" timestamp NOT NULL,
  "duration_seconds" integer NOT NULL
);

CREATE TABLE "learned_signs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "sign_id" bigint NOT NULL,
  "learned_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "achievements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "title" varchar(100) NOT NULL,
  "description" varchar(255),
  "why_it_matters" text,
  "icon" varchar(100),
  "condition_type" varchar(30) NOT NULL,
  "condition_value" integer NOT NULL,
  "course_id" bigint,
  "xp_reward" integer NOT NULL DEFAULT 0,
  "order" integer NOT NULL DEFAULT 0
);

CREATE TABLE "user_achievements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "achievement_id" bigint NOT NULL,
  "unlocked_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "type" varchar(30) NOT NULL,
  "title" varchar(150) NOT NULL,
  "body" text NOT NULL,
  "data" jsonb,
  "is_read" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "devices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "platform" varchar(10) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "last_seen_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "dataset_categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "name_ru" varchar(100)
);

CREATE TABLE "dataset_topics" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint,
  "name" varchar(100) NOT NULL,
  "name_ru" varchar(100),
  "description" varchar(255),
  "status" varchar(20) NOT NULL DEFAULT 'approved',
  "proposed_by_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "dataset_words" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_id" bigint NOT NULL,
  "word" varchar(255) NOT NULL,
  "word_ru" varchar(255),
  "description" varchar(255),
  "sign_id" bigint,
  "required_takes" smallint NOT NULL DEFAULT 3,
  "status" varchar(20) NOT NULL DEFAULT 'approved',
  "proposed_by_id" bigint,
  "order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "dataset_word_samples" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word_id" bigint NOT NULL,
  "video" varchar(100) NOT NULL,
  "duration_ms" integer,
  "resolution" varchar(10),
  "order" smallint NOT NULL DEFAULT 0
);

CREATE TABLE "contributions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "word_id" bigint NOT NULL,
  "take_number" smallint NOT NULL,
  "video" varchar(100) NOT NULL,
  "duration_seconds" smallint NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "rejection_reason" varchar(255),
  "reviewed_by_id" bigint,
  "reviewed_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "conversations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "title" varchar(150),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "sender" varchar(20) NOT NULL,
  "input_type" varchar(10) NOT NULL,
  "text" text,
  "input_video" varchar(100),
  "input_audio" varchar(100),
  "output_audio" varchar(100),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "message_signs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id" bigint NOT NULL,
  "sign_id" bigint NOT NULL,
  "order" smallint NOT NULL
);

CREATE TABLE "quick_phrases" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "text" varchar(255) NOT NULL,
  "order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "social_accounts" ("provider", "uid");

CREATE UNIQUE INDEX ON "social_accounts" ("user_id", "provider");

CREATE INDEX ON "phone_otps" ("phone");

CREATE INDEX ON "signs" ("word");

CREATE UNIQUE INDEX ON "sign_categories" ("sign_id", "category_id");

CREATE UNIQUE INDEX ON "sign_related" ("from_sign_id", "to_sign_id");

CREATE UNIQUE INDEX ON "sign_videos" ("sign_id", "angle");

CREATE UNIQUE INDEX ON "saved_signs" ("user_id", "sign_id");

CREATE UNIQUE INDEX ON "recent_views" ("user_id", "sign_id");

CREATE UNIQUE INDEX ON "lesson_signs" ("lesson_id", "sign_id");

CREATE UNIQUE INDEX ON "user_lesson_progress" ("user_id", "lesson_id");

CREATE UNIQUE INDEX ON "exercise_answers" ("attempt_id", "exercise_id");

CREATE UNIQUE INDEX ON "daily_activities" ("user_id", "date");

CREATE INDEX ON "activity_sessions" ("user_id", "started_at");

CREATE UNIQUE INDEX ON "learned_signs" ("user_id", "sign_id");

CREATE UNIQUE INDEX ON "user_achievements" ("user_id", "achievement_id");

CREATE INDEX ON "notifications" ("user_id", "is_read");

CREATE UNIQUE INDEX ON "contributions" ("user_id", "word_id", "take_number");

CREATE INDEX ON "contributions" ("status", "created_at");

ALTER TABLE "social_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "notification_settings" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sign_categories" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sign_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sign_related" ADD FOREIGN KEY ("from_sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sign_related" ADD FOREIGN KEY ("to_sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sign_videos" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_signs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_signs" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recent_views" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recent_views" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_signs" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_signs" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercises" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercises" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercise_options" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercise_options" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_lesson_progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_lesson_progress" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_attempts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_attempts" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercise_answers" ADD FOREIGN KEY ("attempt_id") REFERENCES "lesson_attempts" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercise_answers" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercise_reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercise_reports" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "user_stats" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_activities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activity_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learned_signs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learned_signs" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "achievements" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devices" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_topics" ADD FOREIGN KEY ("category_id") REFERENCES "dataset_categories" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_topics" ADD FOREIGN KEY ("proposed_by_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_words" ADD FOREIGN KEY ("topic_id") REFERENCES "dataset_topics" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_words" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_words" ADD FOREIGN KEY ("proposed_by_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_word_samples" ADD FOREIGN KEY ("word_id") REFERENCES "dataset_words" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("word_id") REFERENCES "dataset_words" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contributions" ADD FOREIGN KEY ("reviewed_by_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "message_signs" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "message_signs" ADD FOREIGN KEY ("sign_id") REFERENCES "signs" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quick_phrases" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
