"""multilingual lesson and sign texts

Revision ID: d8f5494e3320
Revises: b5c1d2e3f4a5
Create Date: 2026-10-07 17:17:22.978718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f5494e3320'
down_revision: Union[str, Sequence[str], None] = 'b5c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('subtitle_ru', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('subtitle_en', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('description_ru', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('description_en', sa.String(length=255), nullable=True))
    op.add_column('exercise_options', sa.Column('text_ru', sa.String(length=255), nullable=True))
    op.add_column('exercise_options', sa.Column('text_en', sa.String(length=255), nullable=True))
    op.add_column('exercises', sa.Column('prompt_ru', sa.String(length=255), nullable=True))
    op.add_column('exercises', sa.Column('prompt_en', sa.String(length=255), nullable=True))
    op.add_column('exercises', sa.Column('explanation_ru', sa.String(length=500), nullable=True))
    op.add_column('exercises', sa.Column('explanation_en', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('title_ru', sa.String(length=150), nullable=True))
    op.add_column('lessons', sa.Column('title_en', sa.String(length=150), nullable=True))
    op.add_column('lessons', sa.Column('description_ru', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('meaning_ru', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('meaning_en', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('hand_shape_ru', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('hand_shape_en', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('movement_ru', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('movement_en', sa.Text(), nullable=True))
    op.add_column('signs', sa.Column('example_sentence_ru', sa.String(length=500), nullable=True))
    op.add_column('signs', sa.Column('example_sentence_en', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signs', 'example_sentence_en')
    op.drop_column('signs', 'example_sentence_ru')
    op.drop_column('signs', 'movement_en')
    op.drop_column('signs', 'movement_ru')
    op.drop_column('signs', 'hand_shape_en')
    op.drop_column('signs', 'hand_shape_ru')
    op.drop_column('signs', 'meaning_en')
    op.drop_column('signs', 'meaning_ru')
    op.drop_column('lessons', 'description_en')
    op.drop_column('lessons', 'description_ru')
    op.drop_column('lessons', 'title_en')
    op.drop_column('lessons', 'title_ru')
    op.drop_column('exercises', 'explanation_en')
    op.drop_column('exercises', 'explanation_ru')
    op.drop_column('exercises', 'prompt_en')
    op.drop_column('exercises', 'prompt_ru')
    op.drop_column('exercise_options', 'text_en')
    op.drop_column('exercise_options', 'text_ru')
    op.drop_column('courses', 'description_en')
    op.drop_column('courses', 'description_ru')
    op.drop_column('courses', 'subtitle_en')
    op.drop_column('courses', 'subtitle_ru')
    # ### end Alembic commands ###
